version: '3.8'

services:
  automl-streamlit:
    container_name: automl_app
    build:
      context: .
      dockerfile: Dockerfile  # This is the default; you can rename your file to something else if needed
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
